name: Build

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt coverage test it:test coverageReport paradox
